### ISSUE TITLE
Library i2c.h

### ISSUE THREAD

**Issue by filcol** [PlayingWithFusion/PWFusion_AS3935_I2C#2]
Can you please confirm which i2c.h library you are using, I find several versions online.

thanks

**Comment by fusionstein** [comment]
Hi,
We're using the one from DSCircuits 
--
Thanks,
Justin
Justin Steinlage
Playing With Fusion, Inc. Thursday, 25 August 2016, 02:19PM -05:00 from filcol  notifications@github.com :

**Comment by filcol** [comment]
ok, that was the one I was using.
