### ISSUE TITLE
Where can i find the I²C.h library

### ISSUE THREAD

**Issue by Nordrunner01** [PlayingWithFusion/PWFusion_AS3935_I2C#4]
Hello

I looking for the library you define in the I²C-Scetch

>  The AS3935 communicates via SPI or I2C. 
// This example uses the I2C interface via the I2C lib, not Wire lib
#include "I2C.h"

Where i can find it?

Regards

**Comment by fusionstein** [comment]
Download from these guys: http://dsscircuits.com/articles/arduino-i2c-master-library
--
Thanks,
Justin
Justin Steinlage
Playing With Fusion, Inc Tuesday, 17 December 2019, 01:54AM -06:00 from Jens Vorwerg  notifications@github.com :
